config/routes.rb
Rails.application.routes.draw do
  # 管理者ルート
  devise_for :admin, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root to: 'customers#index'
    get 'search' => 'searches#search'
    resources :customers, only: [:show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  # ユーザールート
  devise_for :customers, controllers: {
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }

  # ゲストユーザー
  devise_scope :customer do
    post "customers/guest_sign_in", to: "customers/sessions#guest_sign_in"
  end

  scope module: :customers do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    get 'check' => 'customers#check'
    get 'customers/:id/report' => 'customers#report', as: 'customer_report'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customers_withdrawal'
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts do
      get :favorites, on: :collection
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :customer
  belongs_to :post
  validates :comment, presence: true, length: {maximum:100}

end

app/controllers/admins/comments_controller.rb
class Admins::CommentsController < ApplicationController

  before_action :authenticate_admin!

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/customers/comments_controller.rb
class Customers::CommentsController < ApplicationController

  before_action :set_comment, only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = current_customer.comments.new(post_comment_params)
    @comment.post = @post
    @comment.save
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.destroy
    # redirect_to post_path(post)
  end

  private

  def post_comment_params
    params.require(:comment).permit(:comment)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/admins/comments_helper.rb
module Admins::CommentsHelper
end

app/helpers/customers/comments_helper.rb
module Customers::CommentsHelper
end

app/views/admins/comments/_post_comments.html.erb
<div class="row mt-4">
  <div class="col-12">
    <% if post.comments.any? %>
      <h4>コメント</h4>
      <% post.comments.each do |comment| %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-auto">
                <%= image_tag(comment.customer.profile_image, class: "profile-image", size: "100x100") %>
              </div>
              <div class="col">
                <div class="d-flex justify-content-between align-items-center">
                  <h5><%= comment.customer.name %></h5>
                  <small><%= comment.created_at.strftime('%Y/%m/%d') %></small>
                </div>
                <h6><%= comment.comment %></h6>
                <div class="text-right">
                  <%= link_to "削除", admins_post_comment_path(post, comment), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>まだコメントはありません。</p>
    <% end %>
  </div>
</div>