config/routes.rb
Rails.application.routes.draw do
  # 管理者ルート
  devise_for :admin, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root to: 'customers#index'
    get 'search' => 'searches#search'
    resources :customers, only: [:show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  # ユーザールート
  devise_for :customers, controllers: {
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }

  # ゲストユーザー
  devise_scope :customer do
    post "customers/guest_sign_in", to: "customers/sessions#guest_sign_in"
  end

  scope module: :customers do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    get 'check' => 'customers#check'
    get 'customers/:id/report' => 'customers#report', as: 'customer_report'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customers_withdrawal'
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts do
      get :favorites, on: :collection
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: false, length: { maximum: 300 }
  validates :departure_date, presence: true
  validates :return_date, presence: true

  has_many_attached :images
  has_one_attached :profile_image

  belongs_to :customer

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  has_many :comments, dependent: :destroy

  # 投稿機能に画像も投稿
  def get_image(width, height, shape = "rectangle")
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_post_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_fill: [width, height]).processed
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_user_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 旅行期間を計算
  def trip_duration
    days = (return_date - departure_date).to_i + 1
    years = days / 365
    months = (days % 365) / 30
    remaining_days = (days % 365) % 30

    {
      days: days,
      years: years,
      months: months,
      remaining_days: remaining_days
    }
  end
  # 出発日
  def formatted_departure_date
    departure_date.strftime("%Y年%m月%d日")
  end

  # 帰国日
  def formatted_return_date
    return_date.strftime("%Y年%m月%d日")
  end

  # 並び替え機能
  def self.sort_index(sort)
    case sort
    # 投稿の古い順に並び替え
    when 'old'
      order(created_at: :asc)
    # 投稿のいいねが多い順に並び替え
    when 'favorite_count'
      left_joins(:favorites).group('posts.id').order('COUNT(favorites.id) DESC')
    # 投稿のコメントが多い順に並び替え
    when 'comment_count'
      left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
    else
      # 投稿の新しい順に並び替え
      order(created_at: :desc)
    end
  end

  # 検索機能
  def self.search_for(content)
    if content.present?
      where('name LIKE ?', "%#{content}%").order(created_at: :desc)
    else
      order(created_at: :desc)
    end
  end

  def self.search_active_customers(content)
    where(is_deleted: false).search_for(content)
  end

  def self.search_all_customers(content)
    search_for(content)
  end

  
  enum prefecture: {
    hokkaido: 1,
    aomori: 2,
    iwate: 3,
    miyagi: 4,
    akita: 5,
    yamagata: 6,
    fukushima: 7,
    ibaraki: 8,
    tochigi: 9,
    gunma: 10,
    saitama: 11,
    chiba: 12,
    tokyo: 13,
    kanagawa: 14,
    niigata: 15,
    toyama: 16,
    ishikawa: 17,
    fukui: 18,
    yamanashi: 19,
    nagano: 20,
    gifu: 21,
    shizuoka: 22,
    aichi: 23,
    mie: 24,
    shiga: 25,
    kyoto: 26,
    osaka: 27,
    hyogo: 28,
    nara: 29,
    wakayama: 30,
    tottori: 31,
    shimane: 32,
    okayama: 33,
    hiroshima: 34,
    yamaguchi: 35,
    tokushima: 36,
    kagawa: 37,
    ehime: 38,
    kochi: 39,
    fukuoka: 40,
    saga: 41,
    nagasaki: 42,
    kumamoto: 43,
    oita: 44,
    miyazaki: 45,
    kagoshima: 46,
    okinawa: 47
  }

  def self.prefecture_options_for_select
    Post.prefectures.map { |key, value| [value, key] }
  end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @posts = Post.page(params[:page])
    @customer = current_customer
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @customer = Customer.find(@post.customer_id)
    @post.destroy
    redirect_to admins_posts_path, notice: "削除に成功しました。"
  end

end

app/controllers/customers/posts_controller.rb
class Customers::PostsController < ApplicationController
  before_action :authenticate_customer!, except: [:index, :show]
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @posts = Post.joins(:customer).where(customers: { is_deleted: false }).sort_index(params[:sort]).page(params[:page])
    @customer = current_customer
  end

  def new
    @post = Post.new
  end


  def show
    @post = Post.find(params[:id])
    @customer = Customer.find(@post.customer_id)
    if @customer.is_deleted
      redirect_to root_path
      flash[:notice] = "投稿情報は表示できません。"
    else
      @post_comment = Comment.new
      @location = [@post.location]
      @pins = Post.where.not(id: @post.id).pluck(:location, :title)
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
      flash[:notice] = "編集に成功しました。"
    else
      render :edit
    end
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    if @post.save
      flash[:notice] = "投稿に成功しました。"
      redirect_to post_path(@post.id)
    else
      @posts = Post.all
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @customer = Customer.find(@post.customer_id)
    @post.destroy
    redirect_to customer_path(@customer)
    flash[:notice] = "削除に成功しました。"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :map_latitude, :map_longitude, :departure_date, :prefecture, :return_date, images: [], location:[])
  end

  def is_matching_login_user
    post = Post.find(params[:id])
    unless post.customer_id == current_customer.id
      flash[:alert] = "他ユーザーの投稿編集画面には遷移できません。"
      redirect_to post_path(post.id)
    end
  end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/customers/posts_helper.rb
module Customers::PostsHelper
end

app/views/admins/posts/_posts_list.html.erb
<div class="card shadow-lg px-3 py-3" style="overflow-y: auto; max-height: calc(100vh - 240px);">
  <% if @posts.empty? %>
    <p>投稿がありません。</p>
  <% else %>
    <% @posts.each_with_index do |post, index| %>
      <div class="card mb-3 h-100 <% if index < @posts.size - 1 %>mb-2<% end %>">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col-2">
              <%= link_to admins_customer_path(post.customer.id) do %>
                <%= image_tag post.customer.get_profile_image(50, 50), class: "mt-0 rounded-circle" %>
                <h6><%= post.customer.name %></h6>
              <% end %>
            </div>
            <div class="col-10">
              <div class="row">
                <% if post.images.attached? %>
                  <div class="col-3">
                    <%= link_to admins_post_path(post) do %>
                      <h6><%= post.title %></h6>
                      <% post.images.first(1).each do |image| %>
                        <%= image_tag image.variant(resize_to_limit: [150, 150]), class: "d-block" %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
                <div class="<%= post.images.attached? ? 'col-9' : 'col-12' %>">
                  <% if post.content.present? %>
                    <% if post.content.length > 89 %>
                      <%= truncate(post.content, length: 89, omission: '...') %>
                    <% else %>
                      <%= post.content %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/admins/posts/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-lg-9 mx-auto">
      <div class="card shadow-lg px-3 py-3">
        <h2 class="text-center">投稿一覧</h2>
      </div>
      <%= render 'posts_list' %>
    </div>
  </div>
</div>

app/views/admins/posts/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-lg-10 mx-auto">
      <div class="card shadow-lg px-3 py-3 text-center">
        <h2>投稿詳細</h2>
      </div>
      <div class="card shadow-lg px-3 py-3">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col-12 col-lg-8">
              <h5><%= @post.title %></h5>
              <div class="row">
                <div class="col-8">
                  <p>
                    <i class="far fa-calendar-alt"></i>
                    <%= @post.trip_duration[:days] %>日間
                    <%= @post.formatted_departure_date %> から <%= @post.formatted_return_date %>
                  </p>
                </div>
                <div class="col-12">
                  <div class="row">
                    <div class="col-10">
                      <div class="btn-group" role="group">
                        <%= link_to "旅行を削除", admins_post_path, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <% if @post.images.attached? %>
          <% @post.images.each do |image| %>
            <div class="col-4" style="padding-top: 10px; padding-bottom: 10px;">
              <%= image_tag image, width: 300, height: 200 %>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= render 'admins/comments/post_comments',post_comment: @post_comment, post: @post %>
    </div>
  </div>
</div>