config/routes.rb
Rails.application.routes.draw do
  # 管理者ルート
  devise_for :admin, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    root to: 'customers#index'
    get 'search' => 'searches#search'
    resources :customers, only: [:show, :edit, :update]
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  # ユーザールート
  devise_for :customers, controllers: {
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }

  # ゲストユーザー
  devise_scope :customer do
    post "customers/guest_sign_in", to: "customers/sessions#guest_sign_in"
  end

  scope module: :customers do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    get 'search' => 'searches#search'
    get 'check' => 'customers#check'
    get 'customers/:id/report' => 'customers#report', as: 'customer_report'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customers_withdrawal'
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts do
      get :favorites, on: :collection
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %>件エラーがあります。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-info text-center text-white pt-3 footer">
  <div class="container">
    <div class="row">
      <div class="mx-auto text-center">
        <% unless customer_signed_in? %>
          <% if admin_signed_in? %>
            <%= link_to "管理者ページ", admins_root_path, class: "text-white" %>
          <% else %>
            <%= link_to "管理者ページ", admin_session_path, class: "text-white" %>
          <% end %>
        <% end %>
        <p>CopyRight  fight.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="d-flex flex-column">
  <div class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light bg-info navbar-fixed-top">
      <div class="container">
        <% if admin_signed_in? %>
          <%= link_to admins_root_path do %>
            <%= image_tag('logo.png', class: 'logo-image', style: 'width: 200px;') %>
          <% end %>
          <h3 class="navbar-text text-light">管理者ログイン</h3>
        <% else %>
          <%= link_to root_path do %>
            <%= image_tag('logo.png', class: 'logo-image', style: 'width: 200px;') %>
          <% end %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <!--ログイン-->
              <li class="nav-item">
                <%= link_to customer_path(current_customer), class: 'nav-link text-light' do %>
                  <i class="fas fa-user"></i>マイページ
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_post_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-edit"></i>新規投稿
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to posts_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-plane-departure"></i>投稿一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to customers_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i>ユーザー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i>ログアウト
                <% end %>
              </li>
              <div class="form-inline my-2 my-lg-0 flex-grow-1">
                <%= render partial: 'customers/searches/search_form' %>
              </div>
            <% elsif admin_signed_in? %>
              <!--管理者-->
              <li class="nav-item">
                <%= link_to admins_posts_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-plane-departure"></i>投稿一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admins_root_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i>ユーザー一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i>ログアウト
                <% end %>
              </li>
              <div class="form-inline my-2 my-lg-0 flex-grow-1">
                <%= render partial: 'admins/searches/search_form' %>
              </div>
            <% else %>
              <!--非ログイン-->
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i>About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to posts_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-plane-departure"></i>投稿一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i>新規登録
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i>ログイン
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootPrints</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/32be1931c4.js" crossorigin="anonymous"></script>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/chartkick@4.0.3" %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= @classname %>">
    <div class="md-4">
      <%= render 'layouts/header' %>
    </div>
    <%= yield %>
    <div class="fixed-bottom">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

<style>
  body {
    padding-bottom: 95px;
    background-image: url(<%= asset_path('aozora.jpg') %>);
    background-size: cover;
  }
</style>